#use the latest LTS version of Node.js
FROM node:18-alpine

#set the networking dirctory inside the container
WORKDIR /app

#copy package.json and package-lock.json
COPY package*.json ./

#install dependencies
RUN npm install

#copy the rest of your application files
COPY . .

#Expose the port your app run on

#define the cmd to run the app
CMD ["npm", "run" , "dev"]
